import numpy as np

In [36]:
import numpy as np

In [40]:
#1
import numpy as np
print(np._version_)print(np.show_config())

SyntaxError: invalid syntax (Temp/ipykernel_11020/801274746.py, line 3)

In [12]:
#2
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [41]:
#3
x = np.array([1,0,0])
print("original array")
print(x)
print("test whether any of the elements of a given array is non-zero:")
print(np.all(x))
x = np.array([0,1,3])
print("oringinal array")
print(x)
print("test if none of the elements of a given  array is non-zero")
print(np.any(x))

original array
[1 0 0]
test whether any of the elements of a given array is non-zero:
False
oringinal array
[0 1 3]
test if none of the elements of a given  array is non-zero
True


In [43]:
#4
x = np.array([1,0,0,0])
print("original array")
print(x)
print("test whether any of the elements of a given array is zero:")
print(np.all(x))
x = np.array([1,0,0,0])
print("oringinal array")
print(x)
print("test if none of the elements of a given  array is zero")
print(np.any(x))

original array
[1 0 0 0]
test whether any of the elements of a given array is zero:
False
oringinal array
[1 0 0 0]
test if none of the elements of a given  array is zero
True


In [ ]:
#5


In [23]:
#6
a = np.array([1,0,np.nan, np.inf])
print("original array")
print(a)
print("test element-wise for postive and negative infinty")
print(np.isinf(a))
        


original array
[ 1.  0. nan inf]
test element-wise for postive and negative infinty
[False False False  True]


In [44]:
#7
#6
a = np.array([1,0,np.nan, np.inf])
print("original array")
print(a)
print("test element-wise for Nan")
print(np.isnan(a))
        

original array
[ 1.  0. nan inf]
test element-wise for Nan
[False False  True False]


In [45]:
#8
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real numbers:")
print(np.isreal(a))
print("Checking for scalar vector:")
print(np.isscalar(3.1) )
print(np.isscalar([3.1]))

original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real numbers:
[False  True  True  True  True False]
Checking for scalar vector:
True
False


In [46]:
#9
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [47]:
#10
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))




Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [55]:
#11
np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100]) 
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))


Original numbers:
[3 5]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:


ValueError: operands could not be broadcast together with shapes (2,) (10,) 

In [ ]:
#12


In [14]:
#16
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#17
np.random.rand(1)

array([0.43733901])

In [16]:
#18
np.random.rand(15)

array([0.99024929, 0.38050703, 0.02459428, 0.83784251, 0.34289596,
       0.53805102, 0.18868943, 0.79926727, 0.65432362, 0.1399649 ,
       0.11732523, 0.37486276, 0.90568936, 0.49025948, 0.86668438])

In [21]:
#19
v=np.arange(15, 55)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [24]:
#20
v=np.arange(0,12).reshape(3,4)
for i in np.nditer(v):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [28]:
#21
v= np.linspace(5,50,10)
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [29]:
#22
b= np.arange(0,21)
b[9:15] = b[9:15]*1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [47]:
#23
a =np.random.randint(0,10,5)
a

array([2, 8, 0, 8, 3])

In [4]:
#26
arr=np.arange(20,60).reshape(2,20)
rows, columns = arr.shape
print(arr.shape)
print(rows)
columns



(2, 20)
2


20

In [30]:
#27
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#28
m = np.zeros((10,10))
m[0:,0] = 1
m[0:,9] = 1
m[0] = 1
m[9] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
#29
a =np.zeros((5,5))
num = 0
for i in range(5):
    num = num+1
    a[i,i] = num

a


array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [8]:
#30
m = np.zeros((4, 4))
m[::2, 1::2] = 1
m[1::2, ::2] = 1
m

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [11]:
#31
np.arange(27).reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
#32
x = np.array([[0,1],[2,3]])
print("original array:")
print(x)
print("sum of all elements:")
print(x)
print(np.sum(x))
print("sum of each column:")
print(np.sum(x, axis=0))
print("sum of each row:")
print(np.sum(x, axis=1))
x

original array:
[[0 1]
 [2 3]]
sum of all elements:
[[0 1]
 [2 3]]
6
sum of each column:
[2 4]
sum of each row:
[1 5]


array([[0, 1],
       [2, 3]])

In [19]:
#33
x = np.arange(24).reshape(2,3,4)
print("array x:")
print(x)
print("array y")
y = np.arange(4)
print(y)
print("inner of x and y arrays")
print(np.inner(x, y))

array x:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array y
[0 1 2 3]
inner of x and y arrays
[[ 14  38  62]
 [ 86 110 134]]
